### ISSUE TITLE
creating a database using EFCore 

### ISSUE THREAD

**Issue by tckiprotich** [tckiprotich/GroupMailbox#11]
- Entity Framework Core is a popular Object Relational Mapper (ORM) that simplifies the process of creating and managing databases in .NET applications.

**Comment by martuto31** [comment]
Hello, can you give me permission to add branches to your project?

**Comment by tckiprotich** [comment]
Hello Martin,  I trust you are well.
Yes you can do so,
Clone the repository, checkout to a new branch,
Work on the issue you have picked, then create a pull requests

If you need more help, you can reach out to me

**Comment by martuto31** [comment]
Hello,
When I try to push the new branch I get this error:
Pushing #11-Create-Database
Remote: Permission to tckiprotich/GroupMailbox.git denied to martuto31.
Error encountered while pushing to the remote repository: Git failed with a
fatal error.
Git failed with a fatal error.
unable to access 'https://github.com/tckiprotich/GroupMailbox/': The
requested URL returned error: 403

Do you know if it is an access problem or another kind of problem?

Best regards,
Martin

**Comment by tckiprotich** [comment]
Okay, Let me add you as a collaborater, check Mail for invite
